language: go

go:
  - 1.11.x

install:
  - curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s -- -b $(go env GOPATH)/bin v1.12.5
  - go get -t ./...

script:
  - golangci-lint run
  - go test -v ./...
